<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.0.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Untitled 14 Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => 'index.html',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => '',
		'to' => ''
	),
	'fields' => array(
		'custom_U6979' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nama Lengkap',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nama Lengkap\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Alamat Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Alamat Email\' is required.',
				'format' => 'Field \'Alamat Email\' has an invalid email.'
			)
		),
		'custom_U6965' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'No. KTP',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'No. KTP\' is required.'
			)
		),
		'custom_U6957' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Alamat Rumah',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Alamat Rumah\' is required.'
			)
		),
		'custom_U6953' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Kecamatan',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Kecamatan\' is required.'
			)
		),
		'custom_U6949' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Kelurahan',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U6961' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'RT/RW',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'RT/RW\' is required.'
			)
		),
		'custom_U6974' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Lembaga/Organisasi',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Lembaga/Organisasi\' is required.'
			)
		),
		'custom_U6945' => array(
			'order' => 9,
			'type' => 'string',
			'label' => 'Pesan Pengajuan',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Pesan Pengajuan\' is required.'
			)
		)
	)
);

process_form($form);
?>
